services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: secure_university
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d secure_university"]
      interval: 3s
      timeout: 3s
      retries: 15
      start_period: 5s

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_NAME: secure_university
      DB_USER: postgres
      DB_PASS: password
      UPLOAD_DIR: /app/uploads
    volumes:
      - ./uploads:/app/uploads
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3020:80"
    restart: unless-stopped

volumes:
  dbdata: